---
# tasks file for ansible-role-adduser
- name: Add group "{{ username }}"
  group:
    gid: "{{ uid_guid }}"
    name: "{{ username }}"
    state: present

- name: Adding user
  user:
    name: "{{ username }}"
    createhome: true
    group: "{{ username }}"
    password: "{{ username }}"
    shell: /bin/bash
    uid: "{{ uid_guid }}"
    state: present
  become: true
