---
# tasks file for ansible-role-adduser
- name: Add group "{{ as_user }}"
  group:
    gid: "{{ uid_guid }}"
    name: "{{ as_user }}"
    state: present
  become: true

- name: Adding user
  user:
    name: "{{ as_user }}"
    password: "{{ as_user_password | password_hash('sha512') }}"
    createhome: true
    group: "{{ as_user }}"
    password: "{{ as_user }}"
    shell: /bin/bash
    uid: "{{ uid_guid }}"
    state: present
  become: true
